version: "3"

services:
    client:
        container_name: client
        image: www.tobybo.life:5000/centos:latest
        labels:
            project: SXDSH
        restart: 'no'
        stdin_open: 'true'
        tty: 'true'
        network_mode: "host"
        logging:
            driver: json-file
        depends_on:
            - "mongo"
        volumes:
            - ./:/proj
            - /etc/localtime:/etc/localtime
        working_dir: /proj/skynet
        entrypoint: ./entrypoint.sh
        environment:
            - CONF_PATH=../game/etc_client/config

